### PR TITLE
Make oss friendly

### LINKED ISSUE #23: Make changes to make this repo open source friendly
1. Add issue templates
2. add contributions.md
3. add a code of conduct

### PR DESCRIPTION
**Pull request by joshi-kaushal**
let me know if i am missing anything.

fixes #23

### CODE REVIEW

**Comment by Sachin-chaurasiya** [comment]
@joshi-kaushal, Can you link the issue?

**Review by Sachin-chaurasiya — APPROVED** [review]
Great work @joshi-kaushal  🙌🏻,
Thanks for the contributions ✨

**Comment by joshi-kaushal** [comment]
@Sachin-chaurasiya check if I need to make any more changes

**Comment by Sachin-chaurasiya** [comment]
> @Sachin-chaurasiya check if I need to make any more changes

@joshi-kaushal ,Looks good to me.
Cc: @atapas

**Review by atapas — APPROVED** [review]

**Comment by atapas** [comment]
> > @Sachin-chaurasiya check if I need to make any more changes
> 
> @joshi-kaushal ,Looks good to me. Cc: @atapas

Looks Good to me. Please merge @Sachin-chaurasiya

**Pull request merged**
